version: "3.7"
services:
  # 서버 설정
  backend:
    image: pxxnxx/atension:main
    container_name: backend
    hostname: backend
    network_mode: "host"
    env_file:
      - .env
    expose:
      - "8080"
